### ISSUE TITLE
Under EL7, cannot get virt-who to run successfully in the background

### ISSUE THREAD

**Issue by belminf** [virt-who/virt-who#23]
Installed master via RPM.

My `sysconfig` looks like this:

    VIRTWHO_BACKGROUND=1
    VIRTWHO_INTERVAL=600
    VIRTWHO_SATELLITE6=1
    VIRTWHO_ESX=1
    VIRTWHO_ESX_OWNER=snip
    VIRTWHO_ESX_ENV=snip
    VIRTWHO_ESX_SERVER=snip
    VIRTWHO_ESX_USERNAME=snip
    VIRTWHO_ESX_PASSWORD=snip

Tried it with just using `systemd`'s wrapper to the `init` script and it would just hang with this error:

    Aug 25 11:07:35 virtwho01 virt-who: 'QueueHandler' object has no attribute 'stream'
    Aug 25 11:07:36 virtwho01 virt-who: Traceback (most recent call last):
    Aug 25 11:07:36 virtwho01 virt-who: File "/usr/share/virt-who/virtwho.py", line 760, in <module>
    Aug 25 11:07:36 virtwho01 virt-who: exit(1)
    Aug 25 11:07:36 virtwho01 virt-who: File "/usr/share/virt-who/virtwho.py", line 745, in exit
    Aug 25 11:07:36 virtwho01 virt-who: virtWho.terminate()
    Aug 25 11:07:36 virtwho01 virt-who: File "/usr/share/virt-who/virtwho.py", line 350, in terminate
    Aug 25 11:07:36 virtwho01 virt-who: for virt in self.virts:
    Aug 25 11:07:36 virtwho01 virt-who: AttributeError: 'VirtWho' object has no attribute 'virts'

I then created a `systemd` unit file based on the one from the `systemd` branch:

    [Unit]
    Description=Daemon for reporting virtual guest IDs to subscription-manager
    After=syslog.target libvirtd.service network.target
    
    [Service]
    Type=forking
    PIDFile=/var/run/virt-who.pid
    ExecStart=/usr/bin/virt-who
    EnvironmentFile=-/etc/sysconfig/virt-who
    
    [Install]
    WantedBy=multi-user.target

Still same error and hanging.

**Comment by rnovacek** [comment]
What distro do you have? What python version?

**Comment by belminf** [comment]
RHEL7 with python 2.7.5

**Comment by rnovacek** [comment]
Please set VIRTWHO_DEBUG=1 in the sysconfig file and post full log here. Thanks.

**Comment by rnovacek** [comment]
Could you please also try adding

Environment=VIRTWHO_BACKGROUND=0

into your systemd unit (after EnvironmentFile line). Thanks.

**Comment by belminf** [comment]
Set `VIRTWHO_DEBUG` in the `sysconfig` file and disabled `VIRTWHO_BACKGROUND` via the unit file as instructed. Still provided very similar output.

Executed ` systemctl start virt-who` and it hung for about 2 minutes before failing:

    Job for virt-who.service failed. See 'systemctl status virt-who.service' and 'journalctl -xn' for details.

Output of `status`:

    virt-who.service - Daemon for reporting virtual guest IDs to subscription-manager
       Loaded: loaded (/etc/systemd/system/virt-who.service; disabled)
       Active: failed (Result: timeout) since Tue 2015-08-25 11:47:52 EDT; 17min ago
      Process: 16845 ExecStart=/usr/bin/virt-who (code=killed, signal=TERM)
    
    Aug 25 11:46:24 virtwho01 virt-who[16845]: File "/usr/share/virt-who/virtwho.py", line 760, in <module>
    Aug 25 11:46:24 virtwho01 virt-who[16845]: exit(1)
    Aug 25 11:46:24 virtwho01 virt-who[16845]: File "/usr/share/virt-who/virtwho.py", line 745, in exit
    Aug 25 11:46:24 virtwho01 virt-who[16845]: virtWho.terminate()
    Aug 25 11:46:24 virtwho01 virt-who[16845]: File "/usr/share/virt-who/virtwho.py", line 350, in terminate
    Aug 25 11:46:24 virtwho01 virt-who[16845]: for virt in self.virts:
    Aug 25 11:46:24 virtwho01 virt-who[16845]: AttributeError: 'VirtWho' object has no attribute 'virts'
    Aug 25 11:47:52 virtwho01 systemd[1]: virt-who.service operation timed out. Terminating.
    Aug 25 11:47:52 virtwho01 systemd[1]: Failed to start Daemon for reporting virtual guest IDs to subscription-manager.
    Aug 25 11:47:52 virtwho01 systemd[1]: Unit virt-who.service entered failed state.

**Comment by rnovacek** [comment]
It looks like the log is trimmed, it calls exit(1), but the reason to do it is not shown.

Can you please post output of:

`journalctl -u virt-who -b`

**Comment by belminf** [comment]
Sorry, I reverted back to the RH supplied `virt-who` for the time being so I am unable to test.

I suppose we could close this issue until someone else is able to reproduce it---it may have been an issue with my environment specifically.
