### ISSUE TITLE
It more a feature request than an issue. - Please register the vmware hosts using host-names and not UUID in the Satellite 6.

### ISSUE THREAD

**Issue by nokernel** [virt-who/virt-who#5]
Please update virt-who to register vcenter hostnames in Satellite instead of UUID.

**Comment by nokernel** [comment]
I have sent a pull request for this.

https://github.com/virt-who/virt-who/pull/6

**Comment by kallisti5** [comment]
Yeah, please fix this.  Only seeing UUID's in subscription manager is a pain when you have 120+ ESX hosts and multiple vCenter environments.

**Comment by rnovacek** [comment]
Commit f6bed0f683c287c6cbea262978db74c9875bc840 introduces the ability to identify hypervisor by hostname. We're working on reporting more information about the hypervisor that will ease the usage even more, but that requires server-side changes (Satellite 6 and Subscription Asset Manager).
