### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by ares** [virt-who/virt-who#50]
There were couple of useful changes recently. I'd be mostly interested in https://github.com/virt-who/virt-who/commit/5f49a9febd9fc6109afa0250e31bd5efcfecd8e9 and would appreciate if I could use official build instead of my own :-)

**Comment by cnsnyder** [comment]
Absolutely. I will take care of this sometime this week.

**Comment by ares** [comment]
Thanks a lot!

**Comment by cnsnyder** [comment]
New release here: https://github.com/virt-who/virt-who/releases/tag/virt-who-0.19-1
Do you need a build in Fedora or else where as well?

**Comment by ares** [comment]
I guess that wouldn't do any harm but for me the tag is enough I think. Thanks a lot.
